image: alpine

before_script:
- apk update
- apk add doxygen
## Uncomment the following line if you use graphviz dot graphs
- apk add ttf-freefont graphviz

test:
  script:
  - doxygen satnogs-rotator-firmware.doxyfile
  except:
  - master
  
pages:
  script:
  - doxygen satnogs-rotator-firmware.doxyfile
  - mv doxygen_files/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master